let items = [
  {
    id: "001",
    image: "img/s2/s2-img1.webp",
    name: "ACE 2",
    price: "1299.00",
    actualprice: "3999.00",
    rating: "⭐⭐⭐⭐⭐(54)",
    extrainfo: "BT Calling | 1.83' TFT Display",
    category: "watch",
  },
  {
    id: "002",
    image: "img/s2/s2-img2.webp",
    name: "AIRFLOW PLUS",
    price: "899.00",
    actualprice: "4999.00",
    rating: "⭐⭐⭐⭐⭐(70)",
    extrainfo: "13 mm Drives | Bluthooth v5.1",
    category: "earbuds",
  },
  {
    id: "003",
    image: "img/s2/s2-img3.webp",
    name: "BASH PRO",
    price: "3599.00",
    actualprice: "11999.00",
    rating: "⭐⭐⭐⭐⭐(4)",
    extrainfo: "ANC + ENC | Quad MICS",
    category: "headphone",
  },
  {
    id: "004",
    image: "img/s2/s2-img4.webp",
    name: "DROP",
    price: "999.00",
    actualprice: "3499.00",
    rating: "⭐⭐⭐⭐⭐(48)",
    extrainfo: "5W Speaker | 100H Standby",
    category: "speaker",
  },
  {
    id: "005",
    image: "img/s5/s5-img1.webp",
    name: "SCREEN TWS",
    price: "2400.00",
    actualprice: "8999.00",
    rating: "⭐⭐⭐⭐⭐(213)",
    extrainfo: "ANC + ENC | Touch Screen",
    category: "",
  },
  {
    id: "006",
    image: "img/s5/s5-img2.webp",
    name: "BASH",
    price: "2499.00",
    actualprice: "8299.00",
    rating: "⭐⭐⭐⭐⭐(83)",
    extrainfo: "wireless | 40mm Sound Drivers",
    category: "headphone",
  },
  {
    id: "007",
    image: "img/s5/s5-img3.webp",
    name: "ACTIVE 2.0 PLUS",
    price: "2299.00",
    actualprice: "5999.00",
    rating: "⭐⭐⭐⭐⭐(84)",
    extrainfo: `2.1" Display | Gesture Control | BT Calling`,
    category: "watch",
  },
  {
    id: "008",
    image: "img/s5/s5-img4.webp",
    name: "STELLER",
    price: "1499.00",
    actualprice: "5999.00",
    rating: "⭐⭐⭐⭐⭐(6)",
    extrainfo: "ENC + Quad Mics",
    category: "earbuds",
  },
  {
    id: "009",
    image: "img/s5/s5-img5.webp",
    name: "CYCLONE",
    price: "1599.00",
    actualprice: "4999.00",
    rating: "⭐⭐⭐⭐⭐(17)",
    extrainfo: `1.39" Screen | BT Calling`,
    category: "watch",
  },
  {
    id: "010",
    image: "img/s5/s5-img6.webp",
    name: "AERO MAX",
    price: "1499.00",
    actualprice: "5999.00",
    rating: "⭐⭐⭐⭐⭐(36)",
    extrainfo: "ANC + ENC | Upto 30 hrs playtime",
    category: "earbuds",
  },
  {
    id: "011",
    image: "img/s5/s5-img7.webp",
    name: "LAXOR",
    price: "2799.00",
    actualprice: "8999.00",
    rating: "⭐⭐⭐⭐⭐(19)",
    extrainfo: `1.45" Amoled | BT Calling`,
    category: "watch",
  },
  {
    id: "012",
    image: "img/s5/s5-img8.webp",
    name: "BLAZE",
    price: "1999.00",
    actualprice: "8999.00",
    rating: "⭐⭐⭐⭐⭐(10)",
    extrainfo: "50mm Drivers | RGB Lights",
    category: "headphone",
  },
  {
    id: "013",
    image: "img/s9/s9-img2.webp",
    name: "ACE 4",
    price: "1599.00",
    actualprice: "4999.00",
    rating: "⭐⭐⭐⭐⭐(27)",
    extrainfo: "BT Calling | IP67",
    category: "watch",
  },
  {
    id: "014",
    image: "img/s9/s9-img3.webp",
    name: "KO PRO",
    price: "1299.00",
    actualprice: "5999.00",
    rating: "⭐⭐⭐⭐⭐(29)",
    extrainfo: "Bluthooth v5.3 | Touch Control",
    category: "earbuds",
  },
  {
    id: "015",
    image: "img/s9/s9-img4.webp",
    name: "FLAX 3.0",
    price: "2499.00",
    actualprice: "4999.00",
    rating: "⭐⭐⭐⭐⭐(10)",
    extrainfo: "wireless Charging | 3 in 1 | Mag Safe",
    category: "charger",
  },
  {
    id: "016",
    image: "img/viewall/items/img-id16.webp",
    name: "FLOW Lite",
    price: "599.00",
    actualprice: "999.00",
    rating: "⭐⭐⭐⭐⭐(2)",
    extrainfo: "120 Day Battery Life | 2 Modes",
    category: "toothbrush",
  },
  {
    id: "017",
    image: "img/viewall/items/img-id17.webp",
    name: "PD 20W ADAPTOR",
    price: "799.00",
    actualprice: "1499.00",
    rating: "⭐⭐⭐⭐⭐(11)",
    extrainfo: "20W Charging | Type C Adaptor",
    category: "charger",
  },
  {
    id: "018",
    image: "img/viewall/items/img-id18.webp",
    name: "ACE PLUS",
    price: "1399.00",
    actualprice: "4999.00",
    rating: "⭐⭐⭐⭐⭐(91)",
    extrainfo: "IP67 | Metallic Alloy Body",
    category: "watch",
  },
  {
    id: "019",
    image: "img/viewall/items/img-id19.webp",
    name: "ULTRA FLOW",
    price: "999.00",
    actualprice: "2499.00",
    rating: "⭐⭐⭐⭐⭐(51)",
    extrainfo: "31000 Strokes/Min | 6 Modes",
    category: "toothbrush",
  },
  {
    id: "020",
    image: "img/viewall/items/img-id20.webp",
    name: "ULTRA PODS",
    price: "699.00",
    actualprice: "3499.00",
    rating: "⭐⭐⭐⭐⭐(23)",
    extrainfo: "Quick Charging | IPX5 Water Resisstant",
    category: "earbuds",
  },
  {
    id: "021",
    image: "img/viewall/items/img-id21.webp",
    name: "25W PD ADAPTOR",
    price: "899.00",
    actualprice: "1499.00",
    rating: "⭐⭐⭐⭐⭐(3)",
    extrainfo: "PPS Technology",
    category: "charger",
  },
  {
    id: "022",
    image: "img/viewall/items/img-id22.webp",
    name: "KO 2.0",
    price: "2299.00",
    actualprice: "9999.00",
    rating: "⭐⭐⭐⭐⭐(33)",
    extrainfo: "TWS | 13mm Sound Drivers",
    category: "btearphone",
  },
  {
    id: "023",
    image: "img/viewall/items/img-id23.webp",
    name: "15W USB CHARGER",
    price: "499.00",
    actualprice: " 999.00",
    rating: "⭐⭐⭐⭐⭐(1)",
    extrainfo: "Fast Charging | 15 Watt",
    category: "charger",
  },
  {
    id: "024",
    image: "img/viewall/items/img-id24.webp",
    name: "BASH LITE",
    price: "1299.00",
    actualprice: "3999.00",
    rating: "⭐⭐⭐⭐⭐(9)",
    extrainfo: "Bluetooth V5.3 | 3.5mm Audio Jack",
    category: "headphone",
  },
  {
    id: "025",
    image: "img/viewall/items/img-id25.webp",
    name: "CONQUER",
    price: "1999.00",
    actualprice: "3999.00",
    rating: "⭐⭐⭐⭐⭐(41)",
    extrainfo: "2.2 Amoled | BT Calling",
    category: "watch",
  },
  {
    id: "026",
    image: "img/viewall/items/img-id26.webp",
    name: "AECTIC 2.04",
    price: "2499.00",
    actualprice: "8999.00",
    rating: "⭐⭐⭐⭐⭐(29)",
    extrainfo: "2.04 Amoled | BT Calling",
    category: "watch",
  },
  {
    id: "027",
    image: "img/viewall/items/img-id27.webp",
    name: "SOLITUDE TWS",
    price: "1299.00",
    actualprice: "4999.00",
    rating: "⭐⭐⭐⭐⭐(11)",
    extrainfo: "ENC and Smart touch | BT V5.3",
    category: "earbuds",
  },
  {
    id: "028",
    image: "img/viewall/items/img-id28.webp",
    name: "POLAR 2.01",
    price: "5999.00",
    actualprice: "11999.00",
    rating: "⭐⭐⭐⭐⭐(1)",
    extrainfo: "Smartwatch x cluba | BT calling",
    category: "watch",
  },
  {
    id: "029",
    image: "img/viewall/items/img-id29.webp",
    name: "ACTIVE 3.0",
    price: "1799.00",
    actualprice: "5999.00",
    rating: "⭐⭐⭐⭐⭐(47)",
    extrainfo: "1.39 Display | BT calling",
    category: "watch",
  },
  {
    id: "030",
    image: "img/viewall/items/img-id30.webp",
    name: "KO MINI",
    actualprice: "899.00",
    price: "3499.00",
    rating: "⭐⭐⭐⭐⭐(84)",
    extrainfo: "Touch controls | Voice Assistant",
    category: "earbuds",
  },
  {
    id: "601",
    image: "img/s6/s6-img1.1.webp",
    name: "ACTIVE",
    actualprice: "9999.00",
    price: "1999.00",
    rating: "⭐⭐⭐⭐⭐(8)",
    extrainfo: "1.32' Display | BT Calling",
    category: "watch",
  },
  {
    id: "602",
    image: "img/s6/s6-img1.2.webp",
    name: "ARCADE",
    actualprice: "5999.00",
    price: "899.00",
    rating: "⭐⭐⭐⭐⭐(5)",
    extrainfo: "RGB Light | 30hrs Playtime",
    category: "earbuds",
  },
  {
    id: "603",
    image: "img/s6/s6-img1.3.webp",
    name: "STROKE",
    actualprice: "6999.00",
    price: "1599.00",
    rating: "⭐⭐⭐⭐⭐(92)",
    extrainfo: "1.96' Display | AOD",
    category: "watch",
  },
  {
    id: "604",
    image: "img/s6/s6-img2.1.webp",
    name: "ACTIVE 2",
    actualprice: "5999.00",
    price: "2099.00",
    rating: "⭐⭐⭐⭐⭐(12)",
    extrainfo: "AOD | 600 Nits Brightness",
    category: "watch",
  },
  {
    id: "605",
    image: "img/s6/s6-img2.2.webp",
    name: "BASH LITE",
    actualprice: "3999.00",
    price: "1299.00",
    rating: "⭐⭐⭐⭐⭐(42)",
    extrainfo: "Bluthooth V5.3 | 3.5mm Audio Jack",
    category: "headphone",
  },
  {
    id: "606",
    image: "img/s6/s6-img2.3.webp",
    name: "HAMMER AIRFLOW",
    actualprice: "4995.00",
    price: "899.00",
    rating: "⭐⭐⭐⭐⭐(12)",
    extrainfo: "BT v5 | IPX4",
    category: "earbuds",
  },
  {
    id: "607",
    image: "img/s6/s6-img3.1.webp",
    name: "KO PRO",
    actualprice: "5999.00",
    price: "1299.00",
    rating: "⭐⭐⭐⭐⭐(42)",
    extrainfo: "ENC | BT5.3",
    category: "earbuds",
  },
  {
    id: "608",
    image: "img/s6/s6-img3.2.webp",
    name: "ACE ULTRA",
    actualprice: "4999.00",
    price: "2999.00",
    rating: "⭐⭐⭐⭐⭐(36)",
    extrainfo: "AOD | 1.96'Screen",
    category: "watch",
  },
  {
    id: "609",
    image: "img/s6/s6-img3.3.webp",
    name: "BASH MAX",
    actualprice: "8245.00",
    price: "2499.00",
    rating: "⭐⭐⭐⭐⭐(34)",
    extrainfo: "1.65' Display",
    category: "headphone",
  },
  {
    id: "610",
    image: "img/s6/s6-img4.1.webp",
    name: "ULTRAFLOW Plus",
    actualprice: "3999.00",
    price: "2090.00",
    rating: "⭐⭐⭐⭐⭐(27)",
    extrainfo: "Oscillating | 8800 strokes",
    category: "toothbrush",
  },
  {
    id: "611",
    image: "img/s6/s6-img4.2.webp",
    name: "FLOW 2.0",
    actualprice: "1999.00",
    price: "599.00",
    rating: "⭐⭐⭐⭐⭐(24)",
    extrainfo: "AAA Battery | 24000 Stroke/Min",
    category: "toothbrush",
  },
  {
    id: "612",
    image: "img/s6/s6-img4.3.webp",
    name: "ULTRAFLOW 2.0",
    actualprice: "3999.00",
    price: "1744.00",
    rating: "⭐⭐⭐⭐⭐(36)",
    extrainfo: "Magnetic Charging | IPX7",
    category: "toothbrush",
  },
  {
    id: "613",
    image: "img/s6/s6-img5.1.webp",
    name: "ACE 3",
    actualprice: "4,999.00",
    price: "1599.00",
    rating: "⭐⭐⭐⭐⭐(32)",
    extrainfo: "1.85' IPS Display | Rotating crown",
    category: "watch",
  },
  {
    id: "614",
    image: "img/s6/s6-img5.2.webp",
    name: "SPLENDOR",
    actualprice: "2499.00",
    price: "699.00",
    rating: "⭐⭐⭐⭐⭐(12)",
    extrainfo: "Bluthooth Nackband",
    category: "btearphone",
  },
  {
    id: "615",
    image: "img/s6/s6-img5.3.webp",
    name: "ROBUSH",
    actualprice: "8999.00",
    price: "2199.00",
    rating: "⭐⭐⭐⭐⭐(11)",
    extrainfo: "1.96' Amoled Display | AOD",
    category: "watch",
  },
  {
    id: "616",
    image: "img/s6/s6-img6.1.webp",
    name: "G-SHOTS",
    actualprice: "4,999.00",
    price: "999.00",
    rating: "⭐⭐⭐⭐⭐(42)",
    extrainfo: "BT V5.3 | Gaming TWS",
    category: "earbuds",
  },
  {
    id: "617",
    image: "img/s6/s6-img6.2.webp",
    name: "BASH 2.0",
    actualprice: "8245.00",
    price: "2499.00",
    rating: "⭐⭐⭐⭐⭐(72)",
    extrainfo: "BT V5.0 | Deep Bash",
    category: "headphone",
  },
  {
    id: "618",
    image: "img/s6/s6-img6.3.png",
    name: "SMASH",
    actualprice: "4999.00",
    price: "1699.00",
    rating: "⭐⭐⭐⭐⭐(8)",
    extrainfo: `5w Speaker`,
    category: "speaker",
  },
];

let s3SlidesData = [
  {
    id: 301,
    imgSrc: "img/s3/s3-img1.webp",
    imgCutSrc: "img/s3/s3-img1-cut.jpeg",
    caption: "Bluetooth Calling Smartwatch",
    isActive: "active",
    category: "watch",
  },
  {
    id: 302,
    imgSrc: "img/s3/s3-img2.webp",
    imgCutSrc: "img/s3/s3-img2-cut.webp",
    caption: "Hammer Bluetooth Headphones",
    category: "headphone",
  },
  {
    id: 303,
    imgSrc: "img/s3/s3-img3.webp",
    imgCutSrc: "img/s3/s3-img3-cut.webp",
    caption: "True Wireless Earbuds",
    category: "earbuds",
  },
  {
    id: 304,
    imgSrc: "img/s3/s3-img4.webp",
    imgCutSrc: "img/s3/s3-img4-cut.webp",
    caption: "Hammer Electric Toothbrush",
    category: "toothbrush",
  },
];

let s4SlideData = [
  {
    active: "active",
    img1: "img/s4/s4-img1.1.webp",
    img1info: "",
    id1: "026",
    img2: "img/s4/s4-img1.2.webp",
    img2info: "",
    id2: "027",
    img3: "img/s4/s4-img1.3.webp",
    img3info: "",
    id3: "609",
    img4: "img/s4/s4-img1.4.webp",
    img4info: "",
    id4: "028",
    img5: "img/s4/s4-img1.5.webp",
    img5info: "",
    id5: "029",
  },
  {
    img1: "img/s4/s4-img2.1.webp",
    textColor1: "text-dark",
    img1info: "Hammer Ultraflow <br> 31,000 strokes per minutes",
    id1: "019",
    img2: "img/s4/s4-img2.2.webp",
    textColor2: "text-white",
    img2info: `ACE Ultra <br> Biggest 1.96 Display`,
    id2: "608",
    img3: "img/s4/s4-img2.3.webp",
    textColor3: "text-white",
    img3info: "Airflow 2.0 <br> Bluthooth V5.0",
    id3: "606",
    img4: "img/s4/s4-img2.4.webp",
    textColor4: "text-white",
    img4info: "Bash 2.0 <br>Wired & Wireless",
    id4: "617",
    img5: "img/s4/s4-img2.5.webp",
    textColor5: "text-dark",
    img5info: "Ace 4.0 <br> 60 Sports Modes",
    id5: "615",
  },
  {
    img1: "img/s4/s4-img3.1.webp",
    textColor1: "text-white",
    img1info: "KO Mini TWS <br> Earbuds withh Touch Controles",
    id1: "030",
    img2: "img/s4/s4-img3.2.webp",
    textColor2: "text-white",
    img2info: "Twisk Neckband <br> HD Sound Quality",
    id2: "614",
    img3: "img/s4/s4-img3.3.webp",
    textColor3: "text-dark",
    img3info: "Hammer Flow Lite <br> Deep Cleaning",
    id3: "016",
    img4: "img/s4/s4-img3.4.webp",
    textColor4: "text-dark",
    img4info: "PD Adaptor <br> Fast Charging",
    id4: "017",
    img5: "img/s4/s4-img3.5.webp",
    textColor5: "text-white",
    img5info: "Hammer Flow 2.0 <br> 120 Days Batter Life",
    id5: "611",
  },
  {
    active: "active",
    img1: "img/s4/cut/cut-s4-img1.1.webp",
    img1info: "",
    id1: "026",
    img2: "img/s4/cut/cut-s4-img1.2.webp",
    img2info: "",
    id2: "027",
    img3: "img/s4/cut/cut-s4-img1.3.webp",
    img3info: "",
    id3: "609",
    img4: "img/s4/cut/cut-s4-img1.4.webp",
    img4info: "",
    id4: "028",
    img5: "img/s4/cut/cut-s4-img1.5.webp",
    img5info: "",
    id5: "029",
  },
  {
    img1: "img/s4/cut/cut-s4-img2.1.webp",
    textColor1: "text-dark",
    img1info: "Hammer Ultraflow <br> 31,000 strokes per minutes",
    id1: "019",
    img2: "img/s4/cut/cut-s4-img2.2.jpeg",
    textColor2: "text-white",
    img2info: "ACE Ultra <br> Biggest 1.96 Display",
    id2: "608",
    img3: "img/s4/cut/cut-s4-img2.3.webp",
    textColor3: "text-white",
    img3info: "Airflow 2.0 <br> Bluthooth V5.0",
    id3: "606",
    img4: "img/s4/cut/cut-s4-img2.4.webp",
    textColor4: "text-white",
    img4info: "Bash 2.0 <br>Wired & Wireless",
    id4: "617",
    img5: "img/s4/cut/cut-s4-img2.5.webp",
    textColor5: "text-dark",
    img5info: "Ace 4.0 <br> 60 Sports Modes",
    id5: "615",
  },
  {
    img1: "img/s4/cut/cut-s4-img3.1.webp",
    textColor1: "text-white",
    img1info: "KO Mini TWS <br> Earbuds withh Touch Controles",
    id1: "030",
    img2: "img/s4/cut/cut-s4-img3.2.webp",
    textColor2: "text-white",
    img2info: "Twisk Neckband <br> HD Sound Quality",
    id2: "614",
    img3: "img/s4/cut/cut-s4-img3.3.webp",
    textColor3: "text-dark",
    img3info: "Hammer Flow Lite <br> Deep Cleaning",
    id3: "016",
    img4: "img/s4/cut/cut-s4-img3.4.webp",
    textColor4: "text-dark",
    img4info: "PD Adaptor <br> Fast Charging",
    id4: "017",
    img5: "img/s4/cut/cut-s4-img3.5.webp",
    textColor5: "text-white",
    img5info: "PD Adaptor <br> Fast Charging",
    id5: "611",
  },
];

let s6items = [
  {
    s6cardback: [
      {
        id: "601",
        image: "img/s6/s6-img1.1.webp",
        name: "Active",
        extrainfo: "1.39' Display",
        actualprice: "9999.00",
        price: "1999.00",
      },
      {
        id: "602",
        image: "img/s6/s6-img1.2.webp",
        name: "Arcade",
        extrainfo: "RGB Light | 30hrs Playtime",
        actualprice: "5999.00",
        price: "899.00",
      },
      {
        id: "603",
        image: "img/s6/s6-img1.3.webp",
        name: "Stroke",
        extrainfo: "1.96' Display | AOD",
        actualprice: "6999.00",
        price: "1599.00",
      },
    ],
    id: "6001",
    image: "img/s6/s6-img1.webp",
  },
  {
    s6cardback: [
      {
        id: "604",
        image: "img/s6/s6-img2.1.webp",
        name: "Active 2",
        extrainfo: "AOD | 600 Nits Brightness",
        actualprice: "5999.00",
        price: "2099.00",
      },
      {
        id: "605",
        image: "img/s6/s6-img2.2.webp",
        name: "Bash Lite",
        extrainfo: "Bluthooth V5.3 | 3.5mm Audio Jack",
        actualprice: "3999.00",
        price: "1299.00",
      },
      {
        id: "606",
        image: "img/s6/s6-img2.3.webp",
        name: "Hammer Airflow",
        extrainfo: "BT v5 | IPX4",
        actualprice: "4995.00",
        price: "899.00",
      },
    ],
    id: "6002",
    image: "img/s6/s6-img2.webp",
  },
  {
    s6cardback: [
      {
        id: "607",
        image: "img/s6/s6-img3.1.webp",
        name: "KO PRO",
        extrainfo: "ENC | BT5.3",
        actualprice: "5999.00",
        price: "1299.00",
      },
      {
        id: "608",
        image: "img/s6/s6-img3.2.webp",
        name: "ACE Ultra",
        extrainfo: "AOD | 1.96'Screen",
        actualprice: "4999.00",
        price: "2149.00",
      },
      {
        id: "609",
        image: "img/s6/s6-img3.3.webp",
        name: "Bash Max",
        extrainfo: "1.65' Display",
        actualprice: "8245.00",
        price: "2499.00",
      },
    ],
    id: "6003",
    image: "img/s6/s6-img3.webp",
  },
  {
    s6cardback: [
      {
        id: "610",
        image: "img/s6/s6-img4.1.webp",
        name: "Ultraflow Plus",
        extrainfo: "Oscillating | 8800 strokes",
        actualprice: "3999.00",
        price: "2090.00",
      },
      {
        id: "611",
        image: "img/s6/s6-img4.2.webp",
        name: "Flow 2.0",
        extrainfo: "AAA Battery | 24000 Stroke/Min",
        actualprice: "1999.00",
        price: "599.00",
      },
      {
        id: "612",
        image: "img/s6/s6-img4.3.webp",
        name: "Ultraflow 2.0",
        extrainfo: "Magnetic Charging | IPX7",
        actualprice: "3999.00",
        price: "1744.00",
      },
    ],
    id: "6004",
    image: "img/s6/s6-img4.webp",
  },
  {
    s6cardback: [
      {
        id: "613",
        image: "img/s6/s6-img5.1.webp",
        name: "ACE 3",
        extrainfo: "1.85' IPS Display | Rotating crown",
        actualprice: "4999.00",
        price: "1599.00",
      },
      {
        id: "614",
        image: "img/s6/s6-img5.2.webp",
        name: "splendor",
        extrainfo: "Bluthooth Nackband",
        actualprice: "2499.00",
        price: "699.00",
      },
      {
        id: "615",
        image: "img/s6/s6-img5.3.webp",
        name: "ROBUST",
        extrainfo: "1.96' Amoled Display | AOD",
        actualprice: "8999.00",
        price: "2199.00",
      },
    ],
    id: "6005",
    image: "img/s6/s6-img5.webp",
  },
  {
    s6cardback: [
      {
        id: "616",
        image: "img/s6/s6-img6.1.webp",
        name: "G-Shots",
        extrainfo: "BT V5.3 | Gaming TWS",
        actualprice: "4999.00",
        price: "999.00",
      },
      {
        id: "617",
        image: "img/s6/s6-img6.2.webp",
        name: "Bash 2.0",
        extrainfo: "BT V5.0 | Deep Bash",
        actualprice: "8245.00",
        price: "3499.00",
      },
      {
        id: "618",
        image: "img/s6/s6-img6.3.png",
        name: "SMASH",
        extrainfo: `5W Speaker`,
        actualprice: "1699.00",
        price: "4999.00",
      },
    ],
    id: "6006",
    image: "img/s6/s6-img6.webp",
  },
];
